version: '3.8'
services:
  front:
    build: ./public
    ports:
      - 3000:3000
    networks:
      - app-network

  api:
    build: ./server
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
